USE [TestingDb]
GO

/****** Object:  Table [dbo].[SemLog2]    Script Date: 08.12.2017 19:53:25 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SemLog2](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[Timestamp] [datetime2](7) NOT NULL,
	[Environment] [nvarchar](50) NOT NULL,
	[Product] [nvarchar](50) NOT NULL,
	[Logger] [nvarchar](50) NOT NULL,
	[Transaction] [nvarchar](50) NULL,
	[Layer] [nvarchar](50) NOT NULL,
	[Level] [nvarchar](50) NOT NULL,
	[Category] [nvarchar](50) NULL,
	[Snapshot] [nvarchar](max) NULL,
	[Elapsed] [bigint] NULL,
	[Message] [nvarchar](max) NULL,
	[Exception] [nvarchar](max) NULL,
	[CallerMemberName] [nvarchar](200) NULL,
	[CallerLineNumber] [int] NULL,
	[CallerFilePath] [nvarchar](200) NULL,
 CONSTRAINT [PK_SemLog2] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [SemLog2_IX_Environment]    Script Date: 08.12.2017 19:53:25 ******/
CREATE NONCLUSTERED INDEX [SemLog2_IX_Environment] ON [dbo].[SemLog2]
(
	[Environment] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [SemLog2_IX_Layer]    Script Date: 08.12.2017 19:53:25 ******/
CREATE NONCLUSTERED INDEX [SemLog2_IX_Layer] ON [dbo].[SemLog2]
(
	[Layer] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [SemLog2_IX_Level]    Script Date: 08.12.2017 19:53:25 ******/
CREATE NONCLUSTERED INDEX [SemLog2_IX_Level] ON [dbo].[SemLog2]
(
	[Level] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [SemLog2_IX_Logger]    Script Date: 08.12.2017 19:53:25 ******/
CREATE NONCLUSTERED INDEX [SemLog2_IX_Logger] ON [dbo].[SemLog2]
(
	[Logger] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [SemLog2_IX_Product]    Script Date: 08.12.2017 19:53:25 ******/
CREATE NONCLUSTERED INDEX [SemLog2_IX_Product] ON [dbo].[SemLog2]
(
	[Product] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [SemLog2_IX_State]    Script Date: 08.12.2017 19:53:25 ******/
CREATE NONCLUSTERED INDEX [SemLog2_IX_State] ON [dbo].[SemLog2]
(
	[Category] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [SemLog2_IX_Transaction]    Script Date: 08.12.2017 19:53:25 ******/
CREATE NONCLUSTERED INDEX [SemLog2_IX_Transaction] ON [dbo].[SemLog2]
(
	[Transaction] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO


