<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Configurations>Debug;Release</Configurations>
        <Platforms>AnyCPU</Platforms>
        <Nullable>enable</Nullable>
        <LangVersion>default</LangVersion>
        <AssemblyName>Reusable.Disposable</AssemblyName>
        <RootNamespace>Reusable</RootNamespace>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
        <DebugSymbols>true</DebugSymbols>
        <DefineConstants>DEBUG;TRACE</DefineConstants>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
        <DefineConstants>TRACE;RELEASE</DefineConstants>
    </PropertyGroup>

    <PropertyGroup>
        <PackageId>Reusable.Disposable</PackageId>
        <Version>33.0.2</Version>
        <Authors>he-dev</Authors>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="src\" />
    </ItemGroup>

</Project>
